### ISSUE TITLE
A problem with building application after using @interacta/css-labels

### ISSUE THREAD

**Issue by mimatij** [cosmograph-org/cosmos#63]
Hi, recently I started using Cosmos library. I find it very interesting and all worked fine at first, but after I started using node labels with @interacta/css-labels, I encountered a problem with the application build. I thought there was a problem with my code, but after testing the build on the example you provided the same thing occurred.

After I downloaded your example [Adding Node Labels](https://codesandbox.io/s/cosmos-node-labels-hkfplk) locally and ran the command "npm run build", I got the error below.
I'm using Node.js version v16.14.2 and npm version 8.5.0.
Could you, please, provide any help?
```
C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\@interacta\css-labels\dist\index.js: Unexpected token: punc (.)
    at Z.get (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\terser\dist\bundle.min.js:1:525)
    at Object.errorToJson (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\@parcel\utils\src\errorUtils.js:9:20)
    at Pipeline.process (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\Pipeline.js:29:26)
    at async Object.run (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\worker.js:15:12)
    at async Bundler.loadAsset (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\Bundler.js:577:19)
    at async C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\Bundler.js:610:13
    at async Promise.all (index 2)
    at async C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\Bundler.js:610:13
    at async Promise.all (index 4)
    at async Bundler.loadAsset (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\Bundler.js:599:21)
    at async C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\Bundler.js:610:13
    at async Promise.all (index 0)
    at async Bundler.loadAsset (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\Bundler.js:599:21)
    at async Bundler.processAsset (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\Bundler.js:557:5)
    at async PromiseQueue._runJob (C:\Users\Mia\Desktop\cosmos-node-labels\node_modules\parcel-bundler\src\utils\PromiseQueue.js:48:7)
```

**Comment by Stukova** [comment]
Thanks @mimatij!


The `@interacta/css-labels` library uses syntax from ES2020, which may not be supported by all bundlers. 
To resolve this problem, I reduced the syntax to ES2019.

You can try out the beta version **0.0.4-beta.0** of the `@interacta/css-labels` library, which includes these changes.

**Comment by mimatij** [comment]
Thank you very much! 
The build is now passing successfully. :smiley: :tada:
